apiVersion: v1
kind: Pod
metadata:
  name: nfs-test
  namespace: jellyfin
spec:
  restartPolicy: Never
  containers:
    - name: shell
      image: busybox:1.36
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: config
          mountPath: /mnt/config
        - name: media
          mountPath: /mnt/media
  volumes:
    - name: config
      persistentVolumeClaim:
        claimName: nfs-config-pvc
    - name: media
      persistentVolumeClaim:
        claimName: nfs-media-pvc
